using namespace std;
#include"Account.h"
#include <iomanip>
#include <iostream>

class User : public Account
{
private:
	int wins;
	int loses;
	double winPct;
	int winStreak;
	string lastPlay;
	bool prevWin;

public:
	User();
	User(string n, string p, int w, int l, int wp, int ws, string lp, bool pw );
	int getWins();
	void setWins(int w);
	int getLoses();
	void setLoses(int l);
	double getWinPct();
	//cannot set win pct; should be generated by program
	string getLastPlay();
	bool getPrevWin();
	void setPrevWin(bool p);

	//void playGame();
	void writeHistoryToFile();
	void printHistory();
};