using namespace std;
#include"Account.h"
#include <iomanip>
#include <iostream>
#include <list> 

class User : public Account
{
private:
	int wins;
	int loses;
	double winPct;
	int winStreak;
	string lastPlay;
	
	list<User> allUsers;
public:
	User();
	User(string n, string p, int w, int l, int wp, int ws, string lp);
	int getWins();
	void setWins(int w);
	int getLoses();
	void setLoses(int l);
	double getWinPct();
	//cannot set win pct; should be generated by program
	string getLastPlay();
	int getStreak();
	void setStreak(int s);


	list<User> getAllUsers();
	void setAllUsers(list<User> u);
	void addUser(User &newU);

	//void playGame();
	//void writeHistoryToFile();
	void printHistory();
	void loadFile();
	void updateFile();
};